### ISSUE TITLE
Cargo.toml's declared rust-version (1.85) is stale

### ISSUE THREAD

**Issue by brunoarueira** [brunoarueira/thoth-mesh#90]
## Goal

`Cargo.toml` declares `rust-version = "1.85"` (the workspace's stated MSRV), but the code doesn't actually build with 1.85 - `connection.rs`'s `register_peer_link` uses a `let`-chain (`if let Some(listen_addr) = peer_listen_addr && discover.record(...)`), which needs a newer stable compiler than 1.85 actually has (`let`-chains stabilized for the 2024 edition later than that).

This has gone unnoticed because CI (`.github/workflows/ci.yml`) uses `dtolnay/rust-toolchain@stable`, not a pinned version - it always builds with whatever the newest stable release is, so it never actually exercises the declared 1.85 floor. Discovered while building [ADR-0023](../blob/main/docs/adr/0023-packaging-docker-and-systemd.md)'s Dockerfile, which originally pinned `rust:1.85-bookworm` and failed to compile with `error[E0658]:  expressions in this position are unstable`; the Dockerfile was changed to track `rust:1-bookworm` (stable) instead of fixing this.

## Known shape

- Either bump `rust-version` to whatever the actual minimum working version is (needs figuring out precisely - probably the release that stabilized `let`-chains for edition 2024), or pin CI to build against the declared `rust-version` too (e.g. an additional CI job using `dtolnay/rust-toolchain@1.85` or whatever the corrected value is) so this class of drift is caught going forward instead of only found by accident.
- Small enough this probably doesn't need its own ADR - a Cargo.toml field correction plus, if wanted, a CI job addition.

Found while working on #50 (Phase 9 packaging, PR #89).
